# Generated by Django 4.2.23 on 2025-09-01 11:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('client_name', models.CharField(max_length=120)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('period_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom range')], default='weekly', max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=50, max_digits=8)),
                ('date_issued', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_entries', to='billing.invoice')),
            ],
            options={
                'ordering': ['work_date'],
            },
        ),
    ]
