# Generated by Django 4.2.23 on 2025-09-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='period_type',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly'), ('custom', 'Custom range')], default='weekly', max_length=12),
        ),
    ]
