# Generated by Django 4.2.23 on 2025-09-10 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0006_client_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='employee',
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this client was created'),
        ),
        migrations.AlterField(
            model_name='client',
            name='default_hourly_rate',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Default hourly rate for this client', max_digits=8),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, help_text="Client's email address for invoice delivery", max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this client is currently active'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(help_text="Client's full name or company name", max_length=120),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this client was last updated'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who owns this client', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
