# Generated by Django 4.2.23 on 2025-09-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_alter_invoice_invoice_number_and_more'),
    ]

    operations = [
        # Remove the unique constraint from invoice_number
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        # Add unique_together constraint for user and invoice_number
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('user', 'invoice_number')},
        ),
    ]
