# Generated by Django 4.2.23 on 2026-04-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_auto_20250911_0055'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('client', 'invoice_number')},
        ),
    ]
